<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>em</string>
	</array>
	<key>name</key>
	<string>Emerald</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#line-comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#declarations</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#literals</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>declarations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(def)\b\s*([_a-zA-Z][_a-zA-Z0-9]*)\s*(:)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.declaration.emerald</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.emerald</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.colon.emerald</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>([_a-zA-Z][_a-zA-Z0-9]*)</string>
							<key>name</key>
							<string>variable.parameter.emerald</string>
						</dict>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>punctuation.separator.comma.emerald</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.declaration.emerald</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.object.emerald</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.emerald</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.object-parent.emerald</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(object)\b\s*([_a-zA-Z][_a-zA-Z0-9]*)\s*(?:(clones) ([_a-zA-Z][_a-zA-Z0-9]*))?</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(let)\b</string>
					<key>name</key>
					<string>keyword.other.declaration.emerald</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(import|if|then|else|do|end)\b</string>
					<key>name</key>
					<string>keyword.control.emerald</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(for|to|downto|by|while)\b</string>
					<key>name</key>
					<string>keyword.control.loop.emerald</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(clone|clones|super|print|return)\b</string>
					<key>name</key>
					<string>keyword.other.emerald</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(!|&amp;&amp;|\|\|)</string>
					<key>name</key>
					<string>keyword.operator.logical.emerald</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(==|!=|&lt;|&gt;|&lt;=|&gt;=)</string>
					<key>name</key>
					<string>keyword.operator.comparison.emerald</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\||^|&amp;|&lt;&lt;|&gt;&gt;|+|\-|\*|\/|%)</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.emerald</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(=|+=|-=|*=|/=|%=)</string>
					<key>name</key>
					<string>keyword.operator.assignment.emerald</string>
				</dict>
			</array>
		</dict>
		<key>line-comment</key>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.emerald</string>
		</dict>
		<key>literals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(None|True|False)\b</string>
					<key>name</key>
					<string>constant.language.emerald</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(-?[0-9]+(?:\.[0-9]+)?)\b</string>
					<key>name</key>
					<string>constant.numeric.emerald</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.emerald</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.emerald</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b([_a-zA-Z][_a-zA-Z0-9]*)\b</string>
					<key>name</key>
					<string>variable.other.emerald</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.emerald</string>
</dict>
</plist>
